export const ActionTypes = {
    SET_IS_LOGGEDIN: "SET_IS_LOGGEDIN",
    SET_IS_LOGGEDOUT: "SET_IS_LOGGEDOUT",

    SET_USER_PROFILE: "SET_USER_PROFILE",

    SET_USER_PLAYLISTS: "SET_USER_PLAYLISTS",
    SET_SELECTED_PLAYLIST: "SET_SELECTED_PLAYLIST",
    SET_FEATURED_PLAYLISTS: "SET_FEATURED_PLAYLISTS",

    CLEAR_SELECTED_PLAYLIST: "CLEAR_SELECTED_PLAYLIST",
    CLEAR_USER_PROFILE: "CLEAR_USER_PROFILE",
    CLEAR_PLAYLISTS: "CLEAR_PLAYLISTS",

    SET_PLAYER_STATE: "SET_PLAYER_STATE",

    SET_SEARCH_STRING: "SET_SEARCH_STRING"
}